global using API.Extensions;
global using API.Middleware;
global using Domain;
global using FluentValidation.AspNetCore;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc.Authorization;
global using Microsoft.EntityFrameworkCore;
global using Persistence;